/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../../public/models/computer.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const backgroundMaterial = new THREE.MeshStandardMaterial({
  color: "#eca560",
  metalness: 0,
  roughness: 0.7,
  transparent: true,
});

export function Computer(props) {
  const { nodes, materials } = useGLTF("/models/computer.glb");
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.004}
        position-y={0.05}
        position-x={-0.075}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Comp_Screen000_TerminalMaterial_0001.geometry}
            material={materials["TerminalMaterial.002"]}
            position={[18.161, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={212.25}
            castShadow
          />
          <mesh
            geometry={nodes.Comp_Screen002_TerminalMaterial_0001.geometry}
            material={materials["TerminalMaterial.002"]}
            position={[18.161, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={212.25}
            castShadow
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={backgroundMaterial}
        scale={8}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/computer.glb");
